### ISSUE TITLE
Line 13 of Renderer.js

### ISSUE THREAD

**Issue by ezraboley** [badgerloop-software/pod3_dashboard#2]
I believe it might just work on windows so we should find a good mac alternative

**Comment by vkottler** [comment]
What line of code / statement? And is this based on empirical evidence or speculation?

Always post the code and the output in a bug issue like this

**Comment by ezraboley** [comment]
Will do, it wasn't working on both of the Macs that tried it, but it did work on someone else's computer and they had a PC. It is <code>const ip = os.networkInterfaces()['Wi-Fi'][1]['address'];</code> which isn't crucial to the program, it was just put in so whoever was using it wouldn't have to get their ip address everytime they wanted to test if it connected to a locally hosted server.

**Comment by vkottler** [comment]
Is that code trying to get the computers own IP address? Why not use `localhost`?

Won't work on a computer without a network interface named `Wi-Fi` which is going to be most computers

**Comment by vkottler** [comment]
Also, what branch does this pertain to? I don't see any such code in `master`

**Comment by ezraboley** [comment]
It must have been just in my branch but you're right about using localhost, I was just having issues with it for some reason but there is no reason it should end up in the master branch anyway.
