### ISSUE TITLE
Potentially Unnecessary Middle Layer Concern

### ISSUE THREAD

**Issue by vkottler** [badgerloop-software/pod3_dashboard#4]
IF there is a server entity (currently [pod3_server](https://github.com/badgerloop-software/pod3_server)) shouldn't it be possible for this project to contain front-end assets only, with JavaScript code executing in a browser?

It looks like an HTTP, REST API is being exposed by the server. It's possible to make requests to this API from directly in the browser without any local server-side code so do we necessarily gain anything with an Electron front-end?

**Comment by ezraboley** [comment]
I feel like the dedicated app idea with Electron is still the way to go because having a dedicated 'Badgerloop App' was something that we were hoping for from the start. Plus I feel like it doesn't add hardly any complexity at this point since the electron part seems like its mostly all taken care of.  What do you mean when you say that we could make all the requests directly in the browser?

**Comment by vkottler** [comment]
What responsibility does pod3_server have and what responsibility does pod3_dashboard have?

Having those two repositories makes sense in the case where the UI (i.e. pod3_dashboard) calls an HTTP API to the backend (pod3_server) to get the data, then does all of the rendering on its own.

The server can then be responsible for accepting and storing incoming telemetry packets from the pod.

If the UI is only making HTTP requests, that can be done with client-side JavaScript in the browser, so what would be the point of using Electron?

Using Electron is mainly for having access to assets locally on the computer it gets installed to (file system, lower level networking etc.).

We can still use it but I would strongly consider figuring out what we're getting out of Electron versus something we can render directly in the browser. If there aren't any Electron-specific features or benefits then we should definitely not use it

**Comment by vkottler** [comment]
Don't think there are any action items so closing
