### ISSUE TITLE
CDN's

### ISSUE THREAD

**Issue by jordanjones98** [badgerloop-software/pod3_dashboard#5]
In index.html a CDN is being pulled in, this needs to be taken out, and made local this app can not talk to the internet at all.

Here is the line

```<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>```

**Comment by ezraboley** [comment]
Good point, I removed them from my branch and updated the package.json appropriately. Ill push to the master once I make sure that it's all good
